### ISSUE TITLE
error： brew services start v2raya

### ISSUE THREAD

**Issue by yxplus1116** [v2rayA/homebrew-v2raya#3]
brew services start v2raya
Error: undefined method plist_startup' for #<Formula v2raya (stable) /usr/local/Homebrew/Library/Taps/v2raya/homebrew-v2raya/Formula/v2raya.rb> Did you mean? plist_name /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/service.rb:43:inplist_startup?’
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:229:in launchctl_load' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:359:inblock in start’
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:290:in each' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:290:instart’
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/lib/services_cli.rb:94:in run!' /usr/local/Homebrew/Library/Taps/homebrew/homebrew-services/cmd/services.rb:48:inservices’
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in public_send' /usr/local/Homebrew/Library/Homebrew/brew.rb:94:in

‘
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
https://github.com/homebrew/homebrew-services/issues/new

**Comment by MarksonHon** [comment]
@yxplus1116 brew let you report an issue to themself, but you reported it to here? LOL

**Comment by yxplus1116** [comment]
> @yxplus1116 brew let you report an issue to themself, but you reported it to here? LOL

![image](https://github.com/v2rayA/homebrew-v2raya/assets/40259902/0f1f8b58-a953-4a3d-aad8-50c1ca69ebe8)

**Comment by MarksonHon** [comment]
@yxplus1116 No error on Linux, so homebrew-v2raya's ruby scripts all work well. Homebrew on your macOS device cannot transform ruby script to the Launchd service config, this is the issue of homebrew-services, NOT us.

**Comment by MarksonHon** [comment]
@MarksonHon https://img2.imgtp.com/2024/05/07/pkomxxnq.png

**Comment by yxplus1116** [comment]
> @MarksonHon https://img2.imgtp.com/2024/05/07/pkomxxnq.png

Well, thank you for your guidance

**Comment by yxplus1116** [comment]
> @MarksonHon https://img2.imgtp.com/2024/05/07/pkomxxnq.png

I see. Thanks again for your help   :)
