### ISSUE TITLE
Manually modify the configuration file automatically restored after restarting the service

### ISSUE THREAD

**Issue by d1ngx** [v2rayA/homebrew-v2raya#4]
My steps:
1. change port of outbonds through `vim "/Users/xxx/Library/Application Support/v2raya/config.json"`
2. `brew services restart v2raya`

But the configuration file automatically restored after restarting the service, manually modifying the configuration file does not take effect.

**Comment by MarksonHon** [comment]
@d1ngx write a Launchd service by yourself and run it with launchctl
