### ISSUE TITLE
Get geosite.dat: dial tcp [::]:443: connect: connection refused

### ISSUE THREAD

**Issue by DanielDeng3** [v2rayA/homebrew-v2raya#5]
Hi , i can't get update about GFW.list, when i click update button,i will get tips as below:
Get "https://raw.githubusercontent.com/v2rayA/dist-v2ray-rules-dat/202409242211/geosite.dat": dial tcp [::]:443: connect: connection refused

Hopefully you guys can fix this problem.
Thanks a lot.

**Comment by DanielDeng3** [comment]
by the way, Platform is macos on m1 chip.
brew install v2raya.

**Comment by MarksonHon** [comment]
@DanielDeng3 Contact the Chinese government and ask them to configure GFW not to block GitHub's domain name, and the masking function will work normally.

**Comment by DanielDeng3** [comment]
> @DanielDeng3 Contact the Chinese government and ask them to configure GFW not to block GitHub's domain name, and the masking function will work normally.

Hi ，I can download.dat file， when I use other policy. just  cat't update  the file  online 。 you think  is DNS  block caused this  problem from  your  reply. I will  try to edit hosts file to check if work. thanks

**Comment by MarksonHon** [comment]
@DanielDeng3 GFW's blocking of GitHub is not just DNS pollution, there should also be connection blocking issues.

Install v2ray or xray directly from brew, then use globally mode, you might be ready to update geoip and geosite.

**Comment by DanielDeng3** [comment]
@MarksonHon thanks,I will try lately
